version: '3.8'

services:
  frontend-builder:
    build:
      context: /tmp/portfolio
      dockerfile: ./webapp/build/Dockerfile.build_webapp
    volumes:
      - build_volume:/app/dist
    env_file:
      - ./build/build_webapp.env

  webapp:
    build:
      context: /tmp/portfolio
      dockerfile: ./webapp/frontend/Dockerfile.nginx_webapp
    container_name: webapp
    volumes:
      - nginx_logs:/var/log/nginx
      - nginx_conf:/etc/nginx
      - build_volume:/usr/share/nginx/html 
    ports:
      - "50080:80"


volumes:
  nginx_logs:
  nginx_conf:
  build_volume:
  

