version: '3'

services:
  web:
    build:
      context: /tmp
      dockerfile: container_web.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ssl-certs:/etc/nginx/ssl
      - sqlite-data:/data

volumes:
  ssl-certs:
  sqlite-data:
