version: '3'
services:
  react-builder:
    image: node:14  # Tu peux utiliser la version de Node.js que tu préfères
    volumes:
      - /home/rocky/new_site:/app
      - build-output:/app/build
    working_dir: /app
    command: /bin/sh

volumes:
  build-output:
