---
- name: Mettre à jour le site web

  hosts: server_ovh
  become: yes
  gather_facts: yes 
  remote_user: rocky

  tasks:
  - name: Synchroniser les répertoires docker
    synchronize: 
      src: "../../docker/"
      dest: "/tmp/docker/"
      delete: yes
      recursive: yes

  - name: Synchroniser les composants swag 
    synchronize:
      src: "../../swag/"
      dest: "/tmp/swag/"
      delete: yes
      recursive: yes
  
  - name: Synchroniser les composants webapp
    synchronize:
      src: "../../webapp/"
      dest: "/tmp/webapp/"
      delete: yes
      recursive: yes


  - name: Synchroniser le répertoire de l'application React vers le serveur
    synchronize:
      src: "../../../frontend/"
      dest: "/tmp/frontend/"
      delete: yes
    become: yes

  #créer les dossiers de volumes nécessaires pour le conteneur swag avec le groupe 9999 et utilisateur 111 ici: /home/rocky/swagconfig avec drwxr-xr-x
  - name: Créer le dossier de configuration du conteneur swag
    file:
      path: /home/rocky/swagconfig
      state: directory
      owner: 111
      group: 9999
      mode: '0755'
    become: yes

  #Créer les dossiers de volumes nécessaires pour le conteneur webapp ici: /var/lib/docker/volumes pour nginx_logs, nginx_conf et build_volume avec root et root
  - name: Créer le dossier nginx logs du conteneur webapp
    file:
      path: /var/lib/docker/volumes/nginx_logs/_data
      state: directory
      owner: root
      group: root
      mode: '0755'
    become: yes

  - name: Créer le dossier nginx conf du conteneur webapp
    file:
      path: /var/lib/docker/volumes/nginx_conf/_data/nginx
      state: directory
      owner: root
      group: root
      mode: '0755'
    become: yes

  - name: Créer le dossier build volume du conteneur webapp
    file:
      path: /var/lib/docker/volumes/build_volume/_data
      state: directory
      owner: root
      group: root
      mode: '0755'
    become: yes


  #Synchroniser le dossier de configuration du conteneur swag avec le serveur distant
  - name: Synchroniser le dossier de configuration du conteneur swag avec le serveur distant
    synchronize:
      src: "../../swag/swagconfig/"
      dest: "/home/rocky/swagconfig/"
    become: yes

  #Synchroniser le dossier de configuration du conteneur webapp avec le serveur distant
  - name: Synchroniser le dossier de configuration du conteneur webapp avec le serveur distant
    synchronize:
      src: "../../webapp/frontend/webappconfig/nginx/"
      dest: "/var/lib/docker/volumes/nginx_conf/_data/nginx/"
    become: yes


  - name: Lancer le conteneur via Docker Compose
    command:
      cmd: "docker compose -f /tmp/docker/docker-compose.yml up -d --build"
      chdir: /tmp/
    become: yes


