---
- name: Copier le Dockerfile et le fichier docker-compose sur le serveur distant
  copy:
    src: "../docker/{{ item }}"
    dest: "/tmp/{{ item }}"
  with_items:
    - container_web.docker-compose.yml
    - container_web.Dockerfile

- name: Synchroniser le répertoire de l'application React vers le serveur
  synchronize:
    src: "../../new_site/"
    dest: "/tmp/new_site/"
    delete: yes
  become: yes

- name: Lancer le conteneur via Docker Compose
  command:
    cmd: "docker compose -f /tmp/container_web.docker-compose.yml up -d --build"
    chdir: /tmp/
  become: yes
